
package appgym;

/**
 *
 * @author HP
 */
import java.awt.Color;
import javax.swing.JFrame;

import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;


class login extends JFrame {
    ConnectionDataBase cn = new ConnectionDataBase();
    Connection conn;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        txtUserName.setBackground(new java.awt.Color(0,0,0,1));
        txtPassword.setBackground(new java.awt.Color(0,0,0, 1));
    }
    
//    private void login(){
//        String uid = txtUserName.getName().toString().trim();
//        String pwd = txtPassword.getName().toString().trim();
//        
//        String user, pass, quyen;
//        
//        StringBuffer sb = new StringBuffer();
//        if(uid.length()>0)
//            sb.append("Tai khoan khong duoc de trong\n");
//        if(pwd.length()>0){
//            sb.append("Mat khau khong duoc de trong\n");
//        }
//        if(sb.length()>0){
//            JOptionPane.showMessageDialog(this, sb.toString());
//            return;
//        }
//        
//        String sql_login = "SELECT * FROM login WHERE uid=? and pwd=?";
//        
//        try {
//            PreparedStatement pst = conn.prepareStatement(sql_login);
//            pst.setString(1, uid);
//            pst.setString(2, pwd);
//            ResultSet rs = pst.executeQuery();
//            if(rs.next()){
//                user = rs.getString("uid");
//                pass = rs.getString("pwd");
//                quyen = rs.getString("quyen");
//                
//                JOptionPane.showMessageDialog(this, "Dang nhap thanh cong!");
//                new HomeLogin(user, pwd).setVisibal(true);
//                this.setVisible(false);
//            }
//            else{
//                JOptionPane.showMessageDialog(this, "Sai tai khoan hoac mat khau!");
//            }
//        } catch (Exception e) {
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        remember = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        forgetPassword = new javax.swing.JLabel();
        clickLogin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        clickSignUp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gym-logo-300_1.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(245, 244, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WELCOM");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 312, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hello! Let's get started");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 312, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Username:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 112, 217, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Password:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 182, -1, 14));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 138, -1, -1));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 202, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user_name.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 138, -1, 32));

        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pass_20.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel3.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/password_view_20pixel.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel3.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        remember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        remember.setText("Remember");
        remember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberActionPerformed(evt);
            }
        });
        jPanel3.add(remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 234, -1, -1));

        jLabel12.setText("__________________________");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 140, 227, 30));

        txtUserName.setFont(txtUserName.getFont());
        txtUserName.setBorder(null);
        jPanel3.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 180, 40));

        jLabel13.setText("__________________________");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 220, 20));

        txtPassword.setFont(txtPassword.getFont());
        txtPassword.setBorder(null);
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 180, 30));

        forgetPassword.setText("Foget password?");
        forgetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(forgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 239, -1, -1));

        clickLogin.setBackground(new java.awt.Color(0, 153, 255));
        clickLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clickLogin.setForeground(new java.awt.Color(255, 255, 255));
        clickLogin.setText("Login");
        clickLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                clickLoginMouseMoved(evt);
            }
        });
        clickLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clickLoginMouseExited(evt);
            }
        });
        clickLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickLoginActionPerformed(evt);
            }
        });
        jPanel3.add(clickLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 276, 249, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Don't have a acount?");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 333, -1, -1));

        clickSignUp.setBackground(new java.awt.Color(245, 244, 244));
        clickSignUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clickSignUp.setText("Sign up");
        clickSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickSignUp.setOpaque(true);
        clickSignUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                clickSignUpMouseMoved(evt);
            }
        });
        clickSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSignUpMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clickSignUpMouseExited(evt);
            }
        });
        jPanel3.add(clickSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 333, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cancel_1.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, 460));

        setSize(new java.awt.Dimension(750, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void rememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberActionPerformed
        // TODO add your handling code here:
        // Check box remember password

    }//GEN-LAST:event_rememberActionPerformed

    private void clickLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickLoginActionPerformed
         String username=txtUserName.getText();
       String password=new String(txtPassword.getPassword());
       
       if(userlogin.checkLogin(username, password))
       { 
        this.dispose(); // dong cua so hien tai
        
       new Home(username);
        
       }else{
            JOptionPane.showMessageDialog(null, "Invalid username or password.");
       }
      
    }//GEN-LAST:event_clickLoginActionPerformed

    private void clickSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSignUpMouseClicked
      //
        test a=new test();
        a.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_clickSignUpMouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        // TODO add your handling code here:
        txtPassword.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setVisible(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        // TODO add your handling code here:
        txtPassword.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setVisible(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void clickLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickLoginMouseMoved
        clickLogin.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_clickLoginMouseMoved

    private void clickLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickLoginMouseExited
        clickLogin.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_clickLoginMouseExited

    private void clickSignUpMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSignUpMouseMoved
        clickSignUp.setForeground(new Color(0,102,255));
    }//GEN-LAST:event_clickSignUpMouseMoved

    private void clickSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSignUpMouseExited
        clickSignUp.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_clickSignUpMouseExited

    /**
     * @param args the command line arguments
     */
//    public void display() {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new login().setVisible(true);
//            }
//        });
//    }
//    java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new login().setVisible(true);
//            }
//        });
    public void startLogin() {
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clickLogin;
    private javax.swing.JLabel clickSignUp;
    private javax.swing.JLabel disable;
    private javax.swing.JLabel forgetPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox remember;
    private javax.swing.JLabel show;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
